### ISSUE TITLE
Support for doctrine/cache:2.1.1

### ISSUE THREAD

**Issue by joanna-bak-sourceability** [consistence-community/consistence-doctrine#7]
Could you add support for newer doctrine cache version?
Currently it breaks due to : 
Fatal error: Class "Doctrine\Common\Cache\ArrayCache" not found in EnumPostLoadEntityListener

**Comment by Amunak** [comment]
As a workaround since this package thankfully uses proper service configuration you can redefine their cache service, for example like this:

```yaml
# config/packages/cache.yaml
framework:
    cache:
        pools:
            enum_cache:
                adapter: cache.adapter.array # or anything else you feel like would work here

services:
    enum_cache_adapter:
        class: \Doctrine\Common\Cache\Psr6\DoctrineProvider
        factory: ['\Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap']
        arguments:
            - '@enum_cache'

    consistence.doctrine.enum.enum_fields_cache_default: '@enum_cache_adapter'
```

The [DoctrineProvider class](https://github.com/doctrine/cache/blob/2.1.x/lib/Doctrine/Common/Cache/Psr6/DoctrineProvider.php) is supplied with Doctrine\Cache since 1.11 (and is included in 2.*).

In Symfony it is provided until 6.0 as `\Symfony\Component\Cache\DoctrineProvider` so you can use that instead if you don't have/want Doctrine\Cache for some reason.
